---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sso

patches:
  - patch: |-
      - op: replace
        path: /spec/channel
        value: 'alpha'
      - op: replace
        path: /spec/installPlanApproval
        value: 'Manual'
    target:
      kind: Subscription
      name: rhsso-operator
resources:
  - ../../base