apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - operatorgroup.yml
  - subscription.yml
  - namespace.yml
  - ./eventlisteners
  - ./triggertemplates
  - ./pipelines
  - ./tasks